[panini]
# taken from paninicollection.fifa.com
cookie = "_panstwc_session=....; _abck=...."
# endpoint = "https://paninicollection.fifa.com/api/unlock_pack.json"

[panini.try]
code = ""
# request_timeout = 30.0

[panini.bf]
code_base = ""
# state_file = ".fifa-panini-try-code-state.json"
# request_timeout = 30.0
# request_delay = 1.0

[daily-play]
# taken from play.fifa.com
cookie = "_panstwc_session=....; _abck=...."
